---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-thing
  description: Test
  annotations:
    github.com/project-slug: ServerlessOpsIO/test-thing
spec:
  type: api
  lifecycle: production
  owner: group:backstage
  system: system:backstage
  providesApis:
    - resource:test-thing

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: test-thing
  description: |
    Things API
    
    The API to manage things
spec:
  type: openapi
  system: system:backstage
  lifecycle: production
  owner: group:backstage
  definition:
    $text: https://github.com/ServerlessOpsIO/test-thing/blob/main/openapi.yaml
