AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  test-thing

  TEST


Parameters:
  Domain:
    Type: String
    Description: 'Name of Domain'

  System:
    Type: String
    Description: "Name of System"

  Component:
    Type: String
    Description: "Name of Component"

  CodeBranch:
    Type: String
    Description: "Name of GitHub Branch"

Resources:
  MessageTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: MessageId
          AttributeType: S
      KeySchema:
        - AttributeName: MessageId
          KeyType: HASH
      TableName: !Sub "${Domain}-${System}-${Component}-${CodeBranch}-messages"

  MessageQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${Domain}-${System}-${Component}-${CodeBranch}-queue"

  MessageConsumerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.12
      CodeUri: src/
      Environment:
        Variables:
          TABLE_NAME: !Ref MessageTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MessageTable
      Events:
        MessageQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt MessageQueue.Arn
            BatchSize: 10
